[versions]
agp = "8.9.1"
kotlin = "2.0.21"
composeBom = "2023.10.01"
lottieCompose = "5.2.0"
emoji2 = "1.3.0"
lifecycle = "2.7.0"
coil = "3.2.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
emoji2 = { module = "androidx.emoji2:emoji2", version.ref = "emoji2" }

lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottieCompose" }
ui = { module = "androidx.compose.ui:ui" }
ui-text = { module = "androidx.compose.ui:ui-text" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-svg = { module = "io.coil-kt.coil3:coil-svg", version.ref = "coil" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }